substitutions:
  device_name: mitest1
  friendly_name: Test1

esphome:
  name: $device_name
  libraries:
    - milight=https://github.com/VladNord/esphome-milight

external_components:
- source: github://hencou/esphome_components
  components: mi

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mi:
  ce_pin: GPIO4                              #required, default: 4
  csn_pin: GPIO5                             #required, default: 15
  reset_pin: 0                            #optional, default: 0, only needed with LT8900 radio
  radio_interface_type: nrf24             #optional, default: nrf24, possible values: nrf24,lt8900
  packet_repeats: 50                      #optional, default: 50
  listen_repeats: 20                      #optional, default: 20
  state_flush_interval: 5000              #optional, default: 10000
  packet_repeat_throttle_threshold: 200   #optional, default: 200
  packet_repeat_throttle_sensitivity: 0   #optional, default: 0
  packet_repeat_minimum: 3                #optional, default: 3
  enable_automatic_mode_switching: false  #optional, default: false
  rf24_power_level: MAX                   #optional, default: MAX, possible values: MIN, LOW, HIGH, MAX
  rf24_listen_channel: LOW                #optional, default: LOW, possible values: LOW, MID, HIGH
  packet_repeats_per_loop: 10             #optional, default: 10
  rf24_channels:                          #optional, 1-3 values required when used, default: LOW-MID-HIGH, possible values: LOW, MID, HIGH
  - LOW
  - MID
  - HIGH
  on_command_received:                    #optional, useful to send remote commands to HA and process them further there in automations
  - homeassistant.event:
      event: esphome.mi_command_received
      data:
        device_id: !lambda 'return format_hex(data.device_id);'
        group_id: !lambda 'return data.group_id;'
        remote_type: !lambda 'return data.remote_type.c_str();'
        command: !lambda 'return data.command.c_str();'

light:
- platform: mi                            #required
  id: light1                              #required
  name: ${friendly_name}                  #required
  device_id: 0xAB01                       #required, hexadacimal value of MiLight id
  group_id: 1                             #required, 1-4 or 1-8, depending on remote type
  remote_type: rgb_cct                    #required, possible values: rgb_cct, rgb, cct, rgbw, fut089, fut091, fut020
  default_transition_length: 0s           #optional, but 0s gives a better behaviour instead the default 200ms
# optional variables: all variables of ESPHome base light component

binary_sensor:
- platform: gpio
  id: d1
  pin:
    number: D1
    mode: INPUT_PULLUP
    inverted: True
  on_multi_click:
  - timing:
    - ON for at most 0.5s
    - OFF for at least 0.5s
    then:
      light.toggle: light1
  - timing:
    - ON for at least 1s
    then:
    - light.turn_on:
        id: light1
        brightness: 0.01
        effect: 'None'
    - while:
        condition:
          binary_sensor.is_on: d1
        then:
        - light.dim_relative:
            id: light1
            relative_brightness: 7%
        - delay: 0.3s
  - timing:
    - ON for at most 0.5s
    - OFF for at most 0.5s
    - ON for at most 0.5s
    - OFF for at least 0.5s
    then:
      light.turn_on:
        id: light1
        effect: night_mode
  - timing:
    - ON for at most 0.5s
    - OFF for at most 0.5s
    - ON for at most 0.5s
    - OFF for at most 0.5s
    - ON for at most 0.5s
    - OFF for at least 0.5s
    then:
      light.turn_on:
        id: light1
        color_mode: COLOR_TEMPERATURE
        color_temperature: 370 mireds

#button possbile since HA version 2021.12
button:
- platform: mi
  id: pair
  name: ${friendly_name} pair
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct
  command: pair
  entity_category: config
- platform: mi
  id: unpair
  name: ${friendly_name} unpair
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct
  command: unpair
  entity_category: config
